<!doctype html>
<html>
<head>
	<meta charset="utf-8">
    <meta content="telephone=no" name="format-detection" />
    <title>TB-PHP-TEST</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0,user-scalable=no" >
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
</head>

<body class="energy team">
</body>
    <H1>think bit</H1>
</html>
